work_dir: ./work_dir/ntu120/xset/paring_test

# feeder
feeder: feeders.feeder_parsing.Feeder
test_feeder_args:
  debug: False
  random_interval: False
  temporal_rgb_frames: 9
  split: test
  sample_path: data/ntu120/xset/CTR_NTU120_XSet_valsample.txt
  label_path: data/ntu120/xset/CTR_NTU120_XSet_vallabel.txt

# model
model: net.inceptionV3.Model
model_args:
  num_class: 120

# test
phase: test
device: [0,1,2,3]

# debug
debug: False
